str = "my name is Maroof Khan"
print(str.endswith("han"))
print(str.capitalize())
print(str.replace("o","a"))
print(str.replace("Maroof","Zaid"))
print(str.find("y"))
print(str.find("is"))
print(str.find("Hello"))
print(str.count("o"))
print(str.count("is"))
print(str.count("Hi"))
